# Generated by Django 5.2.1 on 2025-06-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_quarto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotel.quarto')),
            ],
        ),
    ]
