# Generated by Django 5.2.1 on 2025-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
